//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAM_ControlAsistenciaEntities : DbContext
    {
        public CAM_ControlAsistenciaEntities()
            : base("name=CAM_ControlAsistenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AccesoOpciones> tbl_AccesoOpciones { get; set; }
        public virtual DbSet<tbl_Anio> tbl_Anio { get; set; }
        public virtual DbSet<tbl_Asis_Asistencia> tbl_Asis_Asistencia { get; set; }
        public virtual DbSet<tbl_Asis_Asistencia_Campo> tbl_Asis_Asistencia_Campo { get; set; }
        public virtual DbSet<tbl_Asis_Asistencia_Dispositivos> tbl_Asis_Asistencia_Dispositivos { get; set; }
        public virtual DbSet<tbl_Asis_Configurar_Asistencia_Campo> tbl_Asis_Configurar_Asistencia_Campo { get; set; }
        public virtual DbSet<tbl_Asis_GrupoTablas> tbl_Asis_GrupoTablas { get; set; }
        public virtual DbSet<tbl_Asis_GrupoTablas_Det> tbl_Asis_GrupoTablas_Det { get; set; }
        public virtual DbSet<tbl_Asis_TipoAsistencia> tbl_Asis_TipoAsistencia { get; set; }
        public virtual DbSet<tbl_Asis_Turno> tbl_Asis_Turno { get; set; }
        public virtual DbSet<Tbl_Cargo_Personal> Tbl_Cargo_Personal { get; set; }
        public virtual DbSet<tbl_Definicion_Opciones> tbl_Definicion_Opciones { get; set; }
        public virtual DbSet<TBL_EstadoCelular> TBL_EstadoCelular { get; set; }
        public virtual DbSet<tbl_Estados> tbl_Estados { get; set; }
        public virtual DbSet<tbl_Ges_Local> tbl_Ges_Local { get; set; }
        public virtual DbSet<tbl_Ges_OT_Contable> tbl_Ges_OT_Contable { get; set; }
        public virtual DbSet<tbl_Horario_Personal> tbl_Horario_Personal { get; set; }
        public virtual DbSet<tbl_IngresoPersonal> tbl_IngresoPersonal { get; set; }
        public virtual DbSet<tbl_Mes> tbl_Mes { get; set; }
        public virtual DbSet<tbl_Modelo_Asistencia> tbl_Modelo_Asistencia { get; set; }
        public virtual DbSet<tbl_Personal> tbl_Personal { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
        public virtual DbSet<tbl_Delegacion> tbl_Delegacion { get; set; }
        public virtual DbSet<tbl_Empresa> tbl_Empresa { get; set; }
        public virtual DbSet<tbl_Perfil> tbl_Perfil { get; set; }
    }
}
