//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ges_OT_Contable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Ges_OT_Contable()
        {
            this.tbl_Asis_Asistencia = new HashSet<tbl_Asis_Asistencia>();
            this.tbl_IngresoPersonal = new HashSet<tbl_IngresoPersonal>();
        }
    
        public int id_OtContable { get; set; }
        public Nullable<int> id_Empresa { get; set; }
        public int id_Delegacion { get; set; }
        public string codigo_OTContable { get; set; }
        public string descripcion_OTContable { get; set; }
        public string tipo_OTContable { get; set; }
        public Nullable<System.DateTime> fechaApertura_OTContable { get; set; }
        public Nullable<System.DateTime> fechaBaja_OTContable { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Asis_Asistencia> tbl_Asis_Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IngresoPersonal> tbl_IngresoPersonal { get; set; }
    }
}
