//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Asis_GrupoTablas_Det
    {
        public int id_grupoDetalle { get; set; }
        public Nullable<int> id_Grupo { get; set; }
        public string descripcion_grupoDetalle { get; set; }
        public string abreviatura_grupoDetalle { get; set; }
        public Nullable<int> orden_grupoDetalle { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        public virtual tbl_Asis_GrupoTablas tbl_Asis_GrupoTablas { get; set; }
    }
}
