//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Asis_Asistencia
    {
        public int id_asistencia { get; set; }
        public Nullable<int> id_Local { get; set; }
        public Nullable<int> id_OTContable { get; set; }
        public Nullable<System.DateTime> fecha_asistencia { get; set; }
        public Nullable<int> id_turno { get; set; }
        public string id_tasi_codigo { get; set; }
        public Nullable<int> id_personal { get; set; }
        public string horaIngreso_Asistencia { get; set; }
        public string horaSalida_Asistencia { get; set; }
        public string total_Asistencia { get; set; }
        public string horaIngreso_Fijo_asistencia { get; set; }
        public string horaSalida_Fijo_asistencia { get; set; }
        public string horatotal_Fijo_asistencia { get; set; }
        public string horaExtra_asistencia { get; set; }
        public string totalHoras_Asistencia { get; set; }
        public string observacion_asistencia { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> usuario_creacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<int> usuario_edicion { get; set; }
        public Nullable<System.DateTime> fecha_edicion { get; set; }
    
        public virtual tbl_Asis_TipoAsistencia tbl_Asis_TipoAsistencia { get; set; }
        public virtual tbl_Asis_Turno tbl_Asis_Turno { get; set; }
        public virtual tbl_Ges_Local tbl_Ges_Local { get; set; }
        public virtual tbl_Ges_OT_Contable tbl_Ges_OT_Contable { get; set; }
        public virtual tbl_Personal tbl_Personal { get; set; }
    }
}
