//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Asis_Asistencia_Campo
    {
        public int id_asistenciaCampo { get; set; }
        public string SerieEquipo { get; set; }
        public System.DateTime fechaHora_Sincronizacion { get; set; }
        public System.DateTime fechaHora_asistenciaCampo { get; set; }
        public int id_personal { get; set; }
        public int id_OtContable { get; set; }
        public string Latitud_asistenciaCampo { get; set; }
        public string Longitud_asistenciaCampo { get; set; }
        public Nullable<int> id_ModoAsistencia { get; set; }
        public string nroObra { get; set; }
        public Nullable<int> idTurno { get; set; }
        public System.DateTime fechaHora_Registro { get; set; }
    
        public virtual tbl_Personal tbl_Personal { get; set; }
    }
}
