//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Horario_Personal
    {
        public int id_personal { get; set; }
        public string lunes_I { get; set; }
        public string lunes_S { get; set; }
        public string Martes_I { get; set; }
        public string Martes_S { get; set; }
        public string Miercoles_I { get; set; }
        public string Miercoles_S { get; set; }
        public string Jueves_I { get; set; }
        public string Jueves_S { get; set; }
        public string Viernes_I { get; set; }
        public string Viernes_S { get; set; }
        public string Sabado_I { get; set; }
        public string Sabado_S { get; set; }
        public string Domingo_I { get; set; }
        public string Domingo_S { get; set; }
    }
}
